services:
  speedrunner:
    build:
      context: .
    container_name: speedrunner
    restart: unless-stopped
    environment:
      - DEVICE_ID=pi-403c60f1-2557-408f-a3c8-ca7acaf034f5
      - CLOUD_BASE=https://netrunner-dashboard.vercel.app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./speedrunner.py:/app/speedrunner.py:ro
